services:
  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./Dockerfiles/Database.Dockerfile
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfiles/Frontend.Dockerfile
    container_name: 'frontend'
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www/
    env_file:
      - .env
  parser:
    container_name: 'parser'
    build:
      dockerfile: ../Dockerfiles/Parser.Dockerfile
      context: ./parser
    env_file:
      - .env
      - .alphavantage
    expose:
      - "88"
    # Uncomment to access swagger
    ports:
      - "88:88"
    volumes:
      - ./parser/:/usr/src/parser/
volumes:
  postgres_data: