services:
  db:
    container_name: db
    build:
      context: ./
      dockerfile: ./Dockerfiles/Database.Dockerfile
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgresdb_data:/var/lib/postgresql/data/
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfiles/Frontend.Dockerfile
    container_name: 'frontend'
    ports:
      - "80:80"
    volumes:
      - ./frontend/:/var/www/
    env_file:
      - .env
volumes:
  postgresdb_data: